config/routes.rb
Rails.application.routes.draw do

  root 'page#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }, skip: [:sessions]
  as :user do
    get 'sign_up' => 'users/registrations#custom_new', :as => :user_signup
    post 'user' => 'users/registrations#custom_create', :as => :user_registration
    get 'sign_in' => 'page#index', :as => :new_user_session
    post 'sign_in' => 'users/sessions#create', :as => :user_session
    delete 'sign_out' => 'users/sessions#destroy', :as => :destroy_user_session
  end

  resources :reports do
    put :confirm, on: :member
    patch :confirm, on: :member
    post :confirm, on: :collection
    get :drafts, on: :collection
  end
  resources :projects
  resources :customers, except: [:show]
  resources :users, only: [:index, :edit, :update]
end

app/models/customer.rb
class Customer < ActiveRecord::Base

  has_many :projects

  validates :name, presence: true

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :without_partner

  def index
    @customers = Customer.all.order(id: :desc)
  end

  def show
  end

  def new
    @customer = Customer.new
  end

  def edit
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to customers_url, notice: '正常に顧客情報が登録されました。'
    else
      render :new
    end
  end

  def update
    if @customer.update(customer_params)
      redirect_to @customer, notice: '正常に顧客情報が更新されました。'
    else
      render :edit
    end
  end

  def destroy
    if @customer.projects.present?
      redirect_to customers_url, alert: 'プロジェクトが登録されているため削除できません。' and return
    end
    @customer.destroy
    redirect_to customers_url, notice: '正常に顧客情報が削除されました。'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_customer
    @customer = Customer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def customer_params
    params.require(:customer).permit(:name)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.haml
= form_for @customer, html: {class: 'form-horizontal'} do |f|
  - if @customer.errors.any?
    .alert.alert-danger
      = "#{@customer.errors.count}件のエラーがあります。"
      %ul
        - @customer.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-6
      = f.text_field :name, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/customers/edit.html.haml
.container

  %ol.breadcrumb
    %li= link_to '顧客一覧', customers_path
    %li.active 顧客編集

  .contents-main
    = render 'form'

app/views/customers/index.html.haml
.container
  .contents-main
    %h1 顧客一覧

    .mb15
      = link_to '新規作成', new_customer_path, class: 'btn btn-info'

    - if @customers.present?
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th= t('activerecord.attributes.customer.name')
            %th 操作
        %tbody
          - @customers.each do |customer|
            %tr
              %td= customer.name
              %td
                = link_to '編集', edit_customer_path(customer), class: 'btn btn-xs btn-info'
                = link_to '削除', customer_path(customer), method: :delete, class: 'btn btn-xs btn-danger', :'data-confirm' => '本当に削除してもよろしいでしょうか？'

    - else
      現在登録されている顧客はいません。

app/views/customers/new.html.haml
.container

  %ol.breadcrumb
    %li= link_to '顧客一覧', customers_path
    %li.active 顧客新規登録

  .contents-main
    = render 'form'