config/routes.rb
Rails.application.routes.draw do

  root 'page#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }, skip: [:sessions]
  as :user do
    get 'sign_up' => 'users/registrations#custom_new', :as => :user_signup
    post 'user' => 'users/registrations#custom_create', :as => :user_registration
    get 'sign_in' => 'page#index', :as => :new_user_session
    post 'sign_in' => 'users/sessions#create', :as => :user_session
    delete 'sign_out' => 'users/sessions#destroy', :as => :destroy_user_session
  end

  resources :reports do
    put :confirm, on: :member
    patch :confirm, on: :member
    post :confirm, on: :collection
    get :drafts, on: :collection
  end
  resources :projects
  resources :customers, except: [:show]
  resources :users, only: [:index, :edit, :update]
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :customer
  has_many :projects_users
  has_many :users, through: :projects_users
  has_many :works

  validates :name, :customer_id, :status, presence: true

  scope :active, -> { where(status: Settings.project.status_types.active) }

  def name_with_customer
    "#{customer.name} / #{name}"
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :without_partner

  def index
    page = params[:page].presence || 1
    @projects = Project.order(id: :desc).page(page).per(Settings.project.per)
  end

  def show
    @year = params[:year].to_i == 0 ? Time.now.year : params[:year].to_i
    @works = {}
    (1..12).each do |month|
     @works[month] = Work.select('reports.user_id AS user_id, users.name AS name, SUM(works.time) AS time').
         joins(:report).
         joins('INNER JOIN users ON reports.user_id = users.id').
         where('works.project_id = ? AND reports.target_date BETWEEN ? AND ?', @project.id, Date.new(@year, month), Date.new(@year, month).end_of_month).
         group('reports.user_id')
    end
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.status = 'active'
    if @project.save
      redirect_to projects_url, notice: '正常にプロジェクト情報が登録されました。'
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: '正常にプロジェクト情報が更新されました。'
    else
      render :edit
    end
  end

  def destroy
    #TODO 削除する前に紐付いてる情報が無いかの確認
    if true
      redirect_to projects_url, alert: '紐付いた日報があるため削除できません。' and return
    end

    @project.destroy
    redirect_to projects_url, notice: '正常にプロジェクト情報が削除されました。'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:customer_id, :name, :status, user_ids: [])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for @project, html: { class: 'form-horizontal' } do |f|
  - if @project.errors.any?
    .alert.alert-danger
      = "#{@project.errors.count}件のエラーがあります。"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :customer_id, class: 'col-sm-2 control-label'
    .col-sm-6
      = f.select :customer_id, options_from_collection_for_select(Customer.all, :id, :name, @project.try(:customer_id)), {}, { class: 'form-control' }
  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-6
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :status, class: 'col-sm-2 control-label'
    .col-sm-6
      %label.radio-inline
        = f.radio_button :status, Settings.project.status_types.active
        = t('activerecord.attributes.project.status_types.active')
      %label.radio-inline
        = f.radio_button :status, Settings.project.status_types.closed
        = t('activerecord.attributes.project.status_types.closed')
  .form-group
    = f.label :user_ids, class: 'col-sm-2 control-label'
    .col-sm-6
      = f.select :user_ids, options_from_collection_for_select(User.all, :id, :name, @project.users.pluck(:id)), {}, { multiple: true, class: 'form-control' }
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

:javascript
  $(function() {
    $('select').select2();
  })

app/views/projects/edit.html.haml
.container

  %ol.breadcrumb
    %li= link_to 'プロジェクト一覧', projects_path
    %li.active プロジェクト編集

  .contents-main
    = render 'form'

app/views/projects/index.html.haml
.container

  .contents-main
    %h1 プロジェクト一覧

    .mb15
      = link_to '新規作成', new_project_path, class: 'btn btn-info'

    - if @projects.present?
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th= t('activerecord.attributes.project.name')
            %th= t('activerecord.attributes.customer.name')
            %th= t('activerecord.attributes.project.status')
            %th 合計作業時間
            %th 操作
        %tbody
          - @projects.each do |project|
            %tr
              %td=link_to project.name, project_path(project)
              %td= project.customer.name
              %td= t("activerecord.attributes.project.status_types.#{project.status}")
              %td= "#{project.works.sum(:time)}時間"
              // TODO project.works.joins(:report).where('reports.status = "active"').sum(:time)
              %td
                = link_to '編集', edit_project_path(project), class: 'btn btn-xs btn-info'
                = link_to '削除', project_path(project), method: :delete, class: 'btn btn-xs btn-danger', :'data-confirm' => '本当に削除してもよろしいでしょうか？'

    - else
      現在登録されているプロジェクトはありません。

app/views/projects/new.html.haml
.container

  %ol.breadcrumb
    %li= link_to 'プロジェクト一覧', projects_path
    %li.active プロジェクト新規登録

  .contents-main
    = render 'form'

app/views/projects/show.html.haml
.container

  %ol.breadcrumb
    %li= link_to 'プロジェクト一覧', projects_path
    %li.active プロジェクト詳細

  .contents-main
    .clearfix.mb15
      .pull-right.mt20
        = link_to '編集', edit_project_path(@project), class: 'btn btn-info'
      %h1= @project.name

    %table.table.table-striped.table-hover
      %tr
        %th= t 'activerecord.attributes.customer.name'
        %td= @project.customer.name
      %tr
        %th= t 'activerecord.attributes.project.status'
        %td= t("activerecord.attributes.project.status_types.#{@project.status}")
      %tr
        %th 合計作業時間
        %td= "#{@project.works.sum(:time)}時間"
      %tr
        %th= t 'activerecord.attributes.project.user_ids'
        %td
          - @project.users.each do |user|
            = user.name
            = ',' if user != @project.users.last

    %h2= "#{@year}年"

    = link_to '＜前の年へ', project_path(@project, year: (@year - 1)), class: 'btn btn-default'
    = link_to '次の年へ＞', project_path(@project, year: (@year + 1)), class: 'btn btn-default'

    - @works.each_slice(4) do |temp_works|
      .works-calendar
        =# temp_works
        - temp_works.each do |month, monthly_works|
          .works-calendar-month
            %table{border: 1}
              %tr
                %th{colspan: 3}= "#{month}月"
              - if monthly_works.present?
                - total_time = monthly_works.map(&:time).sum
                %tr
                  %th= t 'activerecord.attributes.project.user_ids'
                  %th= t 'activerecord.attributes.works.time'
                  %th 稼働率
                - monthly_works.each do |user_works|
                  %tr
                    %td= user_works.name
                    %td.text-right= "#{user_works.time}時間"
                    %td.text-right= "#{((user_works.time / total_time) * 100).round(1)}%"
              %tr
                %th 合計
                %td.text-right{colspan: 2}= "#{total_time || 0}時間"