config/routes.rb
Rails.application.routes.draw do

  root 'page#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }, skip: [:sessions]
  as :user do
    get 'sign_up' => 'users/registrations#custom_new', :as => :user_signup
    post 'user' => 'users/registrations#custom_create', :as => :user_registration
    get 'sign_in' => 'page#index', :as => :new_user_session
    post 'sign_in' => 'users/sessions#create', :as => :user_session
    delete 'sign_out' => 'users/sessions#destroy', :as => :destroy_user_session
  end

  resources :reports do
    put :confirm, on: :member
    patch :confirm, on: :member
    post :confirm, on: :collection
    get :drafts, on: :collection
  end
  resources :projects
  resources :customers, except: [:show]
  resources :users, only: [:index, :edit, :update]
end

app/models/report.rb
class Report < ActiveRecord::Base
  has_many :works, dependent: :destroy
  accepts_nested_attributes_for :works, reject_if: :all_blank, allow_destroy: true

  belongs_to :user

  validates :user_id, :target_date, :status, presence: true
  validates :status, inclusion: Settings.report.status_types.values

  scope :order_update_newest, -> { order('updated_at DESC') }
  scope :draft, -> { where(status: Settings.report.status_types.draft) }
  scope :published, -> { where(status: Settings.report.status_types.published) }

  after_save :update_works_status, if: lambda { self.status == Settings.report.status_types.published }

  def update_works_status
    self.works.each do |work|
      work.status = Settings.work.status_types.published
      work.save
    end
  end

  def draft?
    self.status == Settings.report.status_types.draft
  end

  def published?
    self.status == Settings.report.status_types.published
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    page = params[:page].presence || 1
    if current_user.partner?
      @reports = current_user.reports.published.order_update_newest.page(page).per(Settings.report.per)
    else
      @reports = Report.published.order_update_newest.page(page).per(Settings.report.per)
    end
  end

  def show
    if @report.status == Settings.report.status_types.draft
      redirect_to reports_url, alert: '該当のページは存在しません。'
      return
    end
  end

  def new
    @report = Report.new
    @report.target_date = Date.today
    @projects = current_user.projects.active
    @draft_count = current_user.reports.draft.count
  end

  def edit
    redirect_to reports_url, alert: '編集権限がありません。' and return if @report.user != current_user

    @projects = current_user.projects.active
  end

  def confirm
    # render text: params and return
    @projects = current_user.projects.active

    if request.post?
      @report = Report.new(report_params)
      @report.user_id = current_user.id
    else
      @report = Report.find(params[:id])
      @report.attributes = report_params
    end

    redirect_to reports_url, alert: '編集権限がありません。' and return if @report.user != current_user

    @draft_count = current_user.reports.draft.count
    if params['report']['works_attributes'].blank?
      flash.now[:alert] = 'プロジェクトを追加してください。'
      render :action => request.post? ? :new : :edit and return
    end

    params['report']['works_attributes'].each do |key, work|
      if (work['project_id'].blank?)
        flash.now[:alert] = 'プロジェクトを指定してください。'
        render :action => request.post? ? :new : :edit and return
      end
    end

    unless @report.valid?
      render :action => request.post? ? :new : :edit and return
    end

    if @report.status == Settings.report.status_types.draft && @report.save
      redirect_to reports_url, notice: '下書きが保存されました。' and return
    end
  end

  def create
    # render text: params and return
    @report = Report.new(report_params)
    @report.user_id = current_user.id
    @report.status = Settings.report.status_types.published
    @report.published_at = Time.now
    if @report.save
      ReportMailer.send_report(@report).deliver if Settings.mail.is_send
      redirect_to reports_url, notice: '日報を投稿しました。'
    else
      @projects = current_user.projects.active
      render :new
    end
  end

  def update
    redirect_to reports_url, alert: '編集権限がありません。' and return if @report.user != current_user

    if @report.update(report_params)
      if @report.published_at.blank?
        @report.update_attributes(published_at: Time.now)
        ReportMailer.send_report(@report).deliver if Settings.mail.is_send
      end
      redirect_to @report, notice: '日報を更新しました。'
    else
      render :edit
    end
  end

  def destroy
    unless current_user == @report.user || current_user.user_type == Settings.user_types.admin
      redirect_to reports_url, alert: '削除権限がありません。' and return
    end
    @report.destroy
    redirect_to reports_url, notice: '日報を削除しました。'
  end

  def drafts
    page = params[:page].presence || 1
    @reports = current_user.reports.draft.order_update_newest.page(page).per(Settings.report.per)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_report
    @report = Report.find(params[:id])
  rescue => e
    redirect_to reports_url, alert: '該当のページは存在しません。'
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def report_params
    params.require(:report).permit(:id, :target_date, :question, :impression, :status, works_attributes: [:id, :project_id, :report_id, :time, :detail, :_destroy])
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.haml
= form_for [:confirm, @report], html: { class: 'form-horizontal' } do |f|
  - if @report.errors.any?
    .alert.alert-danger
      = "#{@report.errors.count}件のエラーがあります。"
      %ul
        - @report.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :target_date, class: 'col-sm-2 control-label'
    .col-sm-6
      = f.text_field :target_date, class: 'form-control'

  .works
    = f.fields_for :works do |work|
      = render 'work_fields', f: work

  .form-group
    .col-sm-offset-2.col-sm-10
      = link_to_add_association 'プロジェクトの追加', f, :works, class: 'btn btn-info'
      .mt15
        合計作業時間：
        %span.total-time 0
        時間

  .form-group
    = f.label :question, class: 'col-sm-2 control-label'
    .col-sm-6
      = f.text_area :question, class: 'form-control'

  .form-group
    = f.label :impression, class: 'col-sm-2 control-label'
    .col-sm-6
      = f.text_area :impression, class: 'form-control impression-form'

  = f.hidden_field :status

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit '確認', class: 'btn btn-primary'
      = link_to '下書き保存', '#', class: 'btn btn-info draft' if controller.action_name == 'new'

:javascript
  $(function() {
    $("#report_target_date").datepicker({'dateFormat': 'yy-mm-dd'});

    $('select').select2({
      theme: 'bootstrap',
      placeholder: '選択してください',
      allowClear: true
    });

    if ($('form').attr('method') == 'post' && $('.nested-fields').size() == 0) {
      setTimeout(function() { $('a.add_fields').click(); }, 100);
    }

    calcTotalWorkTime();
    $('input.work-time').blur(function() {
      calcTotalWorkTime();
    });

    $('a.add_fields').
      data('association-insertion-method', 'append').
      data('association-insertion-node', '.works');

    $('.works').on('cocoon:after-insert', function(e, added_work) {
      added_work.find('select').select2({
        theme: 'bootstrap',
        placeholder: '選択してください',
        allowClear: true
      });
      $('input.work-time').blur(function() {
        calcTotalWorkTime();
      });
    })
    .on("cocoon:after-remove", function() {
      calcTotalWorkTime();
    });
  });

  $('input[type="submit"]').click(function(event) {
    $('#report_status').val('#{Settings.report.status_types.published}');
  });

  $('.draft').click(function(event) {
    event.preventDefault();
    $('#report_status').val('#{Settings.report.status_types.draft}');
    $($(this).closest('form')).submit();
  });

  function calcTotalWorkTime() {
    var totalTime = 0;
    console.log('detect');
    $('input.work-time').each(function() {
      totalTime += parseFloat($(this).val());
    });
    $('.total-time').html(totalTime);
  }

app/views/reports/_report.html.haml
- total_work_time = 0
%article.contents-main.single-report.mb15
  %header
    %h1
      = image_tag report.user.gravatar_url, alt: 'gravatar', size: '40x40'
      = report.user.name
      = l(report.target_date, format: :long)

  %section
    %h2
      %i.fa.fa-tasks
      本日の仕事
    - report.works.each do |work|
      %section
        %h3
          %span.glyphicon.glyphicon-menu-right
          = work.project.name_with_customer
          ：
          = "#{work.time}時間"
          - total_work_time += work.time
        = simple_format(h(work.detail))
  %section
    %h2
      %i.fa.fa-clock-o
      合計作業時間
    = "#{total_work_time}時間"
  %section
    %h2
      %i.fa.fa-question
      = t('activerecord.attributes.report.question')
    = simple_format(h(report.question))
    - if report.question.blank?
      %p 特に無し
  %section
    %h2
      %i.fa.fa-comment
      = t('activerecord.attributes.report.impression')
    = simple_format(h(report.impression))
    - if report.impression.blank?
      %p 特に無し

  %footer
    - if report.published_at.present?
      %span.published-at= l(report.published_at, format: :middle)
    - unless ['show', 'drafts'].include? controller.action_name
      = link_to 'パーマリンク', report_path(report)
    - if current_user == report.user
      = link_to '編集', edit_report_path(report)
      = link_to '削除', report_path(report), method: :delete, :'data-confirm' => '本当に削除してもよろしいでしょうか？'

app/views/reports/_work_fields.html.haml
.nested-fields
  = f.hidden_field :id
  .form-group
    = f.label :project_id, class: 'col-sm-2 control-label'
    .col-sm-6
      = f.collection_select :project_id, @projects, :id, :name_with_customer, { include_blank: true }, { class: 'form-control' }

  .form-group
    = f.label :time, class: 'col-sm-2 control-label'
    .col-sm-6
      = f.text_field :time, class: 'form-control work-time'

  .form-group
    = f.label :detail, class: 'col-sm-2 control-label'
    .col-sm-6
      = f.text_area :detail, class: 'form-control'

  .form-group
    .col-sm-offset-2.col-sm-10
      = link_to_remove_association "プロジェクトの削除", f, class: 'btn btn-danger'

app/views/reports/confirm.html.haml
- total_work_time = 0

.container
  %ol.breadcrumb
    %li= link_to 'ホーム', reports_path
    %li.active 日報投稿確認

  %article.contents-main.single-report
    = form_for(@report) do |f|
      %h1= "#{l(@report.target_date, format: :long)}の日報"
      = hidden_field_tag 'report[target_date]', params['report']['target_date']
      = hidden_field_tag 'report[status]', Settings.report.status_types.published

      %section
        %h2
          %i.fa.fa-tasks
          本日の仕事
        - params['report']['works_attributes'].each do |key, work|
          %section
            - if work['id'].present?
              = hidden_field_tag "report[works_attributes][#{key}][id]", work['id']
            = hidden_field_tag "report[works_attributes][#{key}][_destroy]", work['_destroy']
            - if work['_destroy'] == 'false'
              %h3
                %span.glyphicon.glyphicon-menu-right
                = Project.find(work['project_id']).name_with_customer
                ：
                = "#{work['time']}時間"
              = simple_format(h(work['detail']))

              = hidden_field_tag "report[works_attributes][#{key}][project_id]", work['project_id']
              = hidden_field_tag "report[works_attributes][#{key}][time]", work['time']
              - total_work_time += work['time'].to_f if work['time'].present?
              .hidden
                = text_area_tag "report[works_attributes][#{key}][detail]", work['detail'], readonly: true

      %section
        %h2
          %i.fa.fa-clock-o
          合計作業時間
        = "#{total_work_time}時間"


      %section
        %h2
          %i.fa.fa-question
          = t('activerecord.attributes.report.question')
        = simple_format(h(@report.question))
        - if @report.question.blank?
          %p 特に無し
        .hidden
          = text_area_tag 'report[question]', params['report']['question'], readonly: true

      %section
        %h2
          %i.fa.fa-comment
          = t('activerecord.attributes.report.impression')
        = simple_format(h(@report.impression))
        - if @report.impression.blank?
          %p 特に無し
        .hidden
          = text_area_tag 'report[impression]', params['report']['impression'], readonly: true

      - if request.post? || @report.published_at.blank?
        = f.submit '投稿する', class: 'btn btn-primary'
      - else
        = f.submit '更新する', class: 'btn btn-primary'
      = link_to '戻る', '#', class: 'btn btn-default', onClick: 'history.back(); return false;'

app/views/reports/drafts.html.haml
.container

  %ol.breadcrumb
    %li= link_to 'ホーム', reports_path
    %li.active 日報下書き一覧

  %h1 下書き一覧

  - if @reports.blank?
    %p 下書きの日報はありません。

  = paginate @reports

  - @reports.each do |report|
    = render partial: 'report', locals: {report: report}

  = paginate @reports

app/views/reports/edit.html.haml
.container
  %ol.breadcrumb
    %li= link_to '日報一覧', reports_path
    %li.active 日報編集

  .contents-main
    = render 'form'

app/views/reports/index.html.haml
.container
  .row
    .col-sm-3
      .contents-main
        = image_tag current_user.gravatar_url, alt: 'gravatar', size: '40x40'
        = current_user.name
        .report_num
          %strong レポート数：
          = current_user.reports.count
        .projects
          %strong 参加プロジェクト
          - if current_user.projects.present?
            %ul
              - current_user.projects.each do |project|
                %li= link_to_unless current_user.partner?, project.name_with_customer, project_path(project)
          - else
            %p 現在参加しているプロジェクトはありません。

    .col-sm-9
      = paginate @reports

      - @reports.each do |report|
        = render partial: 'report', locals: {report: report}

      - if @reports.blank?
        .contents-main
          %p 現在投稿された日報はありません。

      = paginate @reports

app/views/reports/new.html.haml
.container
  %ol.breadcrumb
    %li= link_to 'ホーム', reports_path
    %li.active 日報新規投稿

  .contents-main
    - if @draft_count > 0
      .alert.alert-info
        = link_to '下書きの日報があります。続きから書く場合はここをクリック。', drafts_reports_path

    = render 'form'

app/views/reports/show.html.haml
.container
  = render partial: 'report', locals: {report: @report}