config/routes.rb
Rails.application.routes.draw do

  root 'page#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }, skip: [:sessions]
  as :user do
    get 'sign_up' => 'users/registrations#custom_new', :as => :user_signup
    post 'user' => 'users/registrations#custom_create', :as => :user_registration
    get 'sign_in' => 'page#index', :as => :new_user_session
    post 'sign_in' => 'users/sessions#create', :as => :user_session
    delete 'sign_out' => 'users/sessions#destroy', :as => :destroy_user_session
  end

  resources :reports do
    put :confirm, on: :member
    patch :confirm, on: :member
    post :confirm, on: :collection
    get :drafts, on: :collection
  end
  resources :projects
  resources :customers, except: [:show]
  resources :users, only: [:index, :edit, :update]
end

app/views/layouts/application.html.haml
!!! 5
%html{lang: 'ja'}
  %head
    %meta{charset: 'UTF-8'}
    %title= @title || '日報システム'
    = stylesheet_link_tag    'bootstrap_loader', media: 'all'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body

    %nav.navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          %button{type: 'button', class: 'navbar-toggle collapsed', data: { toggle: 'collapse', target: '#navbar' }, aria: { expanded: 'false' }}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to '日報システム', reports_path, class: 'navbar-brand'
        #navbar.navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li= link_to '新規投稿', new_report_path
            - unless current_user.partner?
              %li= link_to 'プロジェクト', projects_path
              %li= link_to '顧客', customers_path
              %li= link_to 'ユーザ', users_path
          %ul.nav.navbar-nav.navbar-right
            %li.dropdown
              = link_to '#', class: 'dropdown-toggle', :'data-toggle' => 'dropdown', role: 'button', aria: { haspopup: true, expanded: false } do
                メニュー
                %span.caret
              %ul.dropdown-menu
                %li= link_to 'ユーザ情報編集', edit_user_path(current_user)
                %li= link_to 'ログアウト', destroy_user_session_path, method: :delete

    = yield

    - if notice.present?
      :javascript
        var n = noty({
          layout: 'topCenter',
          type: 'information',
          text: "#{notice}",
          animation: {
            open: {height: 'toggle'},
            close: {height: 'toggle'},
            easing: 'swing',
            speed: 500
          },
          timeout: 5000
        });

    - if alert.present?
      :javascript
        var n = noty({
          layout: 'topCenter',
          type: 'error',
          text: "#{alert}",
          animation: {
            open: {height: 'toggle'}, // jQuery animate function property object
            close: {height: 'toggle'}, // jQuery animate function property object
            easing: 'swing', // easing
            speed: 500 // opening & closing animation speed
          },
          timeout: 5000
        });